"""empty message

Revision ID: 40801a89fd1d
Revises: 0141377d1b36
Create Date: 2023-11-22 15:40:37.361928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40801a89fd1d'
down_revision = '0141377d1b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('audio_file')

    # ### end Alembic commands ###
