"""empty message

Revision ID: 789fa928f544
Revises: 5d50187696c2
Create Date: 2023-11-29 13:45:58.911705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789fa928f544'
down_revision = '5d50187696c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaboration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_collab',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('collaboration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaboration.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_collab')
    op.drop_table('collaboration')
    # ### end Alembic commands ###
