"""empty message

Revision ID: cddcfe5ecc80
Revises: 46446bc0d264
Create Date: 2023-11-15 21:59:38.851641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cddcfe5ecc80'
down_revision = '46446bc0d264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_type', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_tag_tagtype')
        batch_op.create_index(batch_op.f('ix_tag_tag_type'), ['tag_type'], unique=True)
        batch_op.drop_column('tagtype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagtype', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_tag_tag_type'))
        batch_op.create_index('ix_tag_tagtype', ['tagtype'], unique=False)
        batch_op.drop_column('tag_type')

    # ### end Alembic commands ###
