"""empty message

Revision ID: d2512078512d
Revises: cddcfe5ecc80
Create Date: 2023-11-15 22:00:58.502220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2512078512d'
down_revision = 'cddcfe5ecc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index('ix_tag_tag_type')
        batch_op.create_index(batch_op.f('ix_tag_tag_type'), ['tag_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_tag_type'))
        batch_op.create_index('ix_tag_tag_type', ['tag_type'], unique=False)

    # ### end Alembic commands ###
